//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int order_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime order_date { get; set; }
        public decimal total_amount { get; set; }
        public int status_id { get; set; }
        public string shipping_address { get; set; }
    
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
