//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sizes
    {
        public Sizes()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int size_id { get; set; }
        public string size_name { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
